# Generated by Django 5.0 on 2025-10-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivey_personal_address',
            new_name='delivery_personal_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
