# Generated by Django 5.0 on 2025-10-11 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_delivey_personal_address_order_delivery_personal_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='requires_delivery_adress_is_not_null',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('requires_couriers_delivery', 'not_required'), models.Q(('delivery_personal_address__gte', ''), ('delivery_personal_address__isnull', False)), _connector='OR'), name='requires_delivery_adress_is_not_null'),
        ),
    ]
